// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoundStashKit.Data;

#nullable disable

namespace SoundStashKit.Migrations
{
    [DbContext(typeof(SoundstashDbContext))]
    [Migration("20260312190045_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoundStashKit.Domain.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text")
                        .HasColumnName("coverImagePath");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("packs", (string)null);
                });

            modelBuilder.Entity("SoundStashKit.Domain.PackSample", b =>
                {
                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PackId", "SampleId");

                    b.HasIndex("SampleId");

                    b.ToTable("pack_samples", (string)null);
                });

            modelBuilder.Entity("SoundStashKit.Domain.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Bpm")
                        .HasColumnType("integer")
                        .HasColumnName("bpm");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filePath");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("samples", (string)null);
                });

            modelBuilder.Entity("SoundStashKit.Domain.SampleTag", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("SampleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("sample_tags", (string)null);
                });

            modelBuilder.Entity("SoundStashKit.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SoundStashKit.Domain.PackSample", b =>
                {
                    b.HasOne("SoundStashKit.Domain.Pack", "Pack")
                        .WithMany("Samples")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundStashKit.Domain.Sample", "Sample")
                        .WithMany("Packs")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("SoundStashKit.Domain.SampleTag", b =>
                {
                    b.HasOne("SoundStashKit.Domain.Sample", "Sample")
                        .WithMany("Tags")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundStashKit.Domain.Tag", "Tag")
                        .WithMany("Samples")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SoundStashKit.Domain.Pack", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SoundStashKit.Domain.Sample", b =>
                {
                    b.Navigation("Packs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SoundStashKit.Domain.Tag", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
